### ISSUE TITLE
> install.packages("rusquant") Warning in install.packages :   package ‘rusquant’ is not available (for R version 3.2.3)

### ISSUE THREAD

**Issue by Djafar1985** [bdemeshev/rusquant#1]
> install.packages("rusquant")
Warning in install.packages :
  package ‘rusquant’ is not available (for R version 3.2.3)

how to fix it?

**Comment by bdemeshev** [comment]
The rusquant package is not on CRAN. You may install it
```
install.packages("rusquant", repos="http://R-Forge.R-project.org", type="source")
```
And author's page is 
http://www.algorithmist.ru/p/rusquant.html

**Comment by Djafar1985** [comment]
спасибо! 
вчера был, причём дважды качал его с репозитория CRAN: первый раз в предыдущую версию RStudio, а второй в обновлённую. Вечером настраивал рабочее пространство при запуске и прописала в .First библиотеки, в которых был в том числе и rusquant. А сегодня запускаю, и он куда-то потерялся. Пробую загрузить - нема.

**Comment by Djafar1985** [comment]
вот тотальное решение https://github.com/r8m/rusquant/issues/1
